kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 192.168.117.220:6789
  adminId: admin
  adminSecretName: ceph-admin-secret
  adminSecretNamespace: kube-system
  pool: kube
  userId: kube
  userSecretName: ceph-secret
  imageFormat: "2"
  imageFeatures: "layering"
